spring.application.name=Proyecto_Bancosol
spring.mvc.view.prefix=/WEB-INF/view/
spring.mvc.view.suffix=.jsp

# 1. Conexion Supabase (PostgreSQL)
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.rlomuwrvboawpmnecupr
spring.datasource.password=ProyectoBancosol
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuracion de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
# Muestra las consultas SQL en la consola
spring.jpa.show-sql=true
# Le dice a Hibernate que estamos usando PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.default_batch_fetch_size=100

# 3. Codificación UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true